# Generated by Django 3.0.4 on 2020-04-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200405_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_basket',
            field=models.BooleanField(default=False, verbose_name='В корзине'),
        ),
    ]
