# Generated by Django 3.0.4 on 2020-03-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200331_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
    ]
